# 📘 NumPy Fundamentals

---

## 🔹 What is NumPy?

- Core library for **Scientific Computing** in Python.
- Foundation for **Data Science**, **Machine Learning**, and **Deep Learning**.
- Provides a fast, efficient **N-dimensional array (`ndarray`)**.
- Over **100× faster** than Python lists for numerical operations.
- Standard import:

```python
import numpy as np
```

---

# 🧩 The `ndarray`

The **ndarray** is NumPy's central object.

### Important Attributes

| Attribute | Description |
|-----------|-------------|
| `shape` | Dimensions of the array |
| `dtype` | Data type of elements |
| `size` | Total number of elements |
| `itemsize` | Size of each element (bytes) |
| `ndim` | Number of dimensions |

Example:

```python
a.shape
a.dtype
a.size
a.itemsize
a.ndim
```

---

# 🏗️ Creating Arrays

```python
np.array([1,2,3])

np.zeros((2,3))

np.ones((3,3))

np.full((2,2), 7)

np.eye(3)
```

---

# 🔢 Creating Sequences

```python
np.arange(0,10)

np.linspace(0,1,5)
```

---

# 🎲 Random Arrays

```python
np.random.random((2,2))

np.random.randn(3,3)
```

---

# ⚡ NumPy vs Python Lists

| NumPy Arrays | Python Lists |
|--------------|--------------|
| Faster (C implementation) | Slower |
| Element-wise operations | List repetition |
| Contiguous memory | Non-contiguous memory |
| No `.append()` | Supports `.append()` |

Example:

```python
np.array([1,2,3]) * 2
# [2 4 6]

[1,2,3] * 2
# [1,2,3,1,2,3]
```

---

# 🎯 Indexing

```python
a[0]

a[1,2]
```

---

# ✂️ Slicing

```python
a[1:3]

a[:,0]

a[0,:]
```

---

# ✅ Boolean Indexing

```python
a[a > 2]
```

Returns only elements satisfying the condition.

---

# 🎯 Fancy Indexing

```python
a[[0,2,4]]
```

Retrieve multiple elements using index lists.

---

# 🔄 Reshaping Arrays

```python
a.reshape(2,3)
```

Change shape **without changing data**.

---

# ➕ Adding Dimensions

```python
a[:, np.newaxis]
```

Useful for converting:

- 1D → Column Vector
- 1D → Higher Dimensions

---

# 🔗 Concatenation

```python
np.concatenate((a,b))

np.hstack((a,b))

np.vstack((a,b))
```

---

# 📡 Broadcasting

Allows operations on arrays of **different shapes** automatically.

Example:

```python
a + 5
```

Every element increases by **5**.

---

# ➗ Linear Algebra

### Dot Product

```python
np.dot(a,b)

a @ b
```

---

### Matrix Operations

```python
np.linalg.inv(a)

np.linalg.det(a)

np.linalg.eig(a)

np.linalg.solve(A,b)
```

---

### Compare Arrays

```python
np.allclose(a,b)
```

Useful for comparing floating-point arrays.

---

# 📊 Statistics

```python
a.sum()

a.mean()

a.std()

a.var()
```

Use `axis` to specify direction.

```python
axis=0   # Columns

axis=1   # Rows
```

---

# 📂 Loading Data

```python
np.loadtxt()

np.genfromtxt()
```

Load CSV or text data directly into NumPy arrays.

---

# 📋 Copy vs Reference

❌ Reference Copy

```python
b = a
```

Both variables point to the **same array**.

---

✅ Independent Copy

```python
b = a.copy()
```

Changes to one array **do not affect** the other.

---

# 💡 Quick Tips

- ✅ Import as:

```python
import numpy as np
```

- ✅ Use `.copy()` for independent arrays.
- ✅ Prefer `@` for matrix multiplication.
- ✅ Use `reshape()` instead of creating new arrays.
- ✅ Use `axis=0` → Columns.
- ✅ Use `axis=1` → Rows.
- ✅ Broadcasting makes NumPy concise and efficient.

---

# 🚀 Most Frequently Used NumPy Functions

```python
np.array()          # Create a NumPy array from a Python list or tuple

np.zeros()          # Create an array filled with zeros

np.ones()           # Create an array filled with ones

np.full()           # Create an array filled with a specified value

np.eye()            # Create an identity matrix

np.arange()         # Generate evenly spaced values within a given range

np.linspace()       # Generate evenly spaced values between two endpoints

np.random.random()  # Generate random numbers between 0 and 1

np.random.randn()   # Generate random numbers from a normal (Gaussian) distribution

np.reshape()        # Change the shape of an array without changing its data

np.concatenate()    # Join two or more arrays along an existing axis

np.hstack()         # Stack arrays horizontally (column-wise)

np.vstack()         # Stack arrays vertically (row-wise)

np.dot()            # Compute the dot product of two arrays

@                   # Matrix multiplication operator

np.linalg.inv()     # Compute the inverse of a square matrix

np.linalg.det()     # Compute the determinant of a matrix

np.linalg.eig()     # Compute eigenvalues and eigenvectors

np.linalg.solve()   # Solve a system of linear equations (Ax = b)

np.sum()            # Compute the sum of array elements

np.mean()           # Compute the average (mean)

np.std()            # Compute the standard deviation

np.var()            # Compute the variance

np.max()            # Return the maximum value

np.min()            # Return the minimum value

np.argmax()         # Return the index of the maximum value

np.argmin()         # Return the index of the minimum value

np.sort()           # Sort an array

np.unique()         # Return unique elements in an array

np.allclose()       # Check if two arrays are approximately equal

np.where()          # Return indices or values based on a condition

np.copy()           # Create an independent copy of an array

np.loadtxt()        # Load numerical data from a text or CSV file

np.genfromtxt()     # Load data from a file while handling missing values
```

In [2]:
import numpy as np

print(f'Numpy Version : {np.__version__}')

Numpy Version : 2.5.1


In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize) # returns in bytes

[1 2 3 4 5]
(5,)
int64
1
5
8


In [4]:
print(a[0])  # Accessing the first element

a[0] = 10  # Modifying the first element

print(a)  # Printing the modified array

1
[10  2  3  4  5]


In [8]:
#Dot Product

b = np.array([6, 7, 8, 6, 1])

dot = np.dot(a, b)
print(f'Dot Product : {dot}')

sum1 = a * b
dot = np.sum(sum1)
print(f'Dot Product : {dot}')

dot2 = a @ b
print(f'Dot Product : {dot2}')

Dot Product : 127
Dot Product : 127
Dot Product : 127


In [ ]:
#Multidimensional (nd) arrays 

c = np.array([[1, 2], [3, 4]])
print(c)
print(c.shape)
print(c[0,1])
print(np.linalg.inv(c))

[[1 2]
 [3 4]]
(2, 2)
2
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Where  
print(f"c = {c[c > 2]}")

d = np.where(c > 2, c, 0)
print(f"d = {d}")

c = [3 4]
d = [[0 0]
 [3 4]]


In [17]:
#Fancy Indexing
a = np.array([1, 2, 3, 4, 5])
indices = [0, 2, 4]
fancy_indexed_array = a[indices]
print(f"Fancy Indexed Array: {fancy_indexed_array}")

Fancy Indexed Array: [1 3 5]


In [20]:
e = np.arange(1,9)
print(f"e = {e}")

print(e.shape)
b = e.reshape(2,4)
print(b)


e = [1 2 3 4 5 6 7 8]
(8,)
[[1 2 3 4]
 [5 6 7 8]]


In [21]:
#Concatenate

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
print(f"Concatenated Array: \n{c}")

Concatenated Array: 
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
d = np.array([[1,2,5,8,9,10], [10,20,30,4,50,62]])
print(d)
print(d.sum(axis=1))  # Sum along columns
print(d.mean(axis=1).round(2))  # Mean along columns

[[ 1  2  5  8  9 10]
 [10 20 30  4 50 62]]
[ 35 176]
[ 5.83 29.33]


In [36]:
x = np.array([1,2])
print(x)
print(x.dtype)

[1 2]
int64


In [48]:
#Generating arrays
a = np.zeros((2, 3))
print(f"Array of zeros: \n{a}")

b = np.ones((3, 2))
print(f"Array of ones: \n{b}")

c = np.full((2, 2), 7)
print(f"Array of sevens: \n{c}")

d = np.eye(3)
print(f"Identity Matrix: \n{d}")

e = np.arange(10)
print(f'arrange numbers = {e}')

f = np.linspace(0, 1, 5)
print(f'linspace numbers = {f}')

g = np.random.rand(2, 3)
print(f'Random numbers = \n{g}')

h = np.random.randint(0, 10, size=(2, 3))
print(f'Random integers = \n{h}')

i = np.random.choice([1, 2, 3, 4, 5], size=(2, 3), replace=True)
print(f'Random choice = \n{i}')


Array of zeros: 
[[0. 0. 0.]
 [0. 0. 0.]]
Array of ones: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Array of sevens: 
[[7 7]
 [7 7]]
Identity Matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arrange numbers = [0 1 2 3 4 5 6 7 8 9]
linspace numbers = [0.   0.25 0.5  0.75 1.  ]
Random numbers = 
[[0.40415359 0.97146876 0.86743928]
 [0.28971613 0.07348742 0.55439053]]
Random integers = 
[[0 8 9]
 [0 6 7]]
Random choice = 
[[2 2 4]
 [4 4 2]]


In [50]:
#Linear Algebra

a = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)

print(f'eigen values = \n{eigenvalues}') 
print(f'eigen vectors = \n{eigenvectors}')

eigen values = 
[-0.37228132+0.j  5.37228132+0.j]
eigen vectors = 
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


In [51]:
a = np.array([1,2,3])
b = np.array([1,2,3])

print(np.allclose(a, b))  # Check if all elements are close to each other

True


In [ ]:
#Solving linear equations

A = np.array([[1,1], [1.5,4.0]])
B = np.array([2200,5050])

x = np.linalg.inv(A).dot(B)
print(x)

y = np.linalg.solve(A,B)
print(y)

[1500.  700.]
[1500.  700.]
